function SNPCA_params = new_SNPCA_params()

SNPCA_params = struct(...
    'chrctrstc_lngth', NaN, ...
    'cnstrnt_rad_fac', NaN, ...
    'new_tri_max_edg_lngth', NaN, ...
    'srch_rad_fac1', NaN, ...
    'srch_rad_fac2', NaN, ...
    'intl_pt_ind', NaN, ...
    'prfrd_cnstrnt_rds', NaN, ...
    'prfrd_cnstrnt_rds_wght', NaN, ...
    'non_adj_tri_dist_tol', NaN, ...
    'cand_vert_max_nudge_dist', NaN, ...
    'adj_vert_max_nudge_dist', NaN, ...    
    'emprcl_drctn_crrltn_eval_bias', NaN, ....
    'nnz_egnvals', NaN, ...
    'emprcl_drctn_egn_sprs_algrthm', false, ...
    'plot_frqncy', NaN, ...
    'max_num_restarts', NaN, ...
    'rtn_mtrx', NaN ...        
    );